In [1]:
# bu benim ilk comment im
# degisken - variable
# integer(tamsayi) degisken- variable
tamsayi_degiskeni = 10 # 10 tamsayisi icin bir degisken tanimladim, bu degiskenin ismi tamsayi_degiskeni
tamsayi_degiskeni2 = 15
print(tamsayi_degiskeni)
print(tamsayi_degiskeni2)

10
15


**Kesirli Sayi**



In [2]:
# kesirli sayi - float
kesirlisayi_degisken = 10.5
print(kesirlisayi_degisken)

10.5


4 işlem özelliği

In [3]:
toplam = tamsayi_degiskeni + tamsayi_degiskeni2
carpma = tamsayi_degiskeni * tamsayi_degiskeni2
cikarma = tamsayi_degiskeni - tamsayi_degiskeni2
bolme = tamsayi_degiskeni / tamsayi_degiskeni2
print(toplam)
print(carpma)
print(cikarma)
print(bolme)

25
150
-5
0.6666666666666666


In [4]:
metin = "hello world" # string - metin
print(metin)

hello world


In [5]:
type(metin)

str

In [6]:
metin1 = "merhaba"
bosluk = " "
metin2 = "dunya"
metin1 + bosluk + metin2

'merhaba dunya'

In [7]:
# f string
# elma: 10 tl
# armut: 20 tl
elma_degisken = 10
armut_degisken = 20
print(f"elma: {elma_degisken} tl, armut: {armut_degisken} tl")
print("elma: {} tl, armut: {} tl".format(elma_degisken, armut_degisken))
# elma: {elma_degisken} tl, armut: {armut_degisken} tl
# elma: 10 tl, armut: 20 tl

elma: 10 tl, armut: 20 tl
elma: 10 tl, armut: 20 tl


Python Syntax

In [8]:
temel = 6
TEMEL = 7
print(temel)
print(TEMEL)

6
7


In [9]:
# COMMENT
"""
 istedigimiz her seyi yazariz kimsade bize karisamaz
"""

'\n istedigimiz her seyi yazariz kimsade bize karisamaz\n'

In [10]:
print(5) # print = build-in function

5


In [11]:
# print = 10

In [12]:
print(5)

5


**Fonksiyonlar**


*   Kullanıcı Tanımlı Fonksiyonlar (User Defined Function)





In [13]:
# dairenin alanını hesaplamak pi*r^2
pi = 3.14
daire_yaricapi = 3
daire_alani = pi*(daire_yaricapi**2)
print(daire_alani)

28.26


In [46]:
def daireAlaniHesapla(daire_yaricapi = 5): # func ismi yazarken islevi belirtmek lazim
  """
    Description: Bu fonksiyon daire alanini hesaplar.
    input parameters: dairenin yaricapi (daire_yaricapi)
    output: dairenin alani (daire_alani)
  """
  PI = 3.14
  daire_alani = PI*(daire_yaricapi**2)
  print(f"Daire Alani: {daire_alani}")
  return daire_alani

In [30]:
daireAlaniHesapla()

Daire Alani: 78.5


In [37]:
user_input  = input("Bir daire yari capi girin: ")
print(f"girilen deger: {user_input} ve bu degerin type: {type(user_input)}")
user_input_int = int(user_input)
print(f"{type(user_input_int)}")
daireAlaniHesapla(user_input_int)

Bir daire yari capi girin: 10
girilen deger: 10 ve bu degerin type: <class 'str'>
<class 'int'>
Daire Alani: 314.0


In [41]:
daire_alani_hesaplanan1 = daireAlaniHesapla(5)
daire_alani_hesaplanan2 = daireAlaniHesapla(3)
print(daire_alani_hesaplanan1 + daire_alani_hesaplanan2)

Daire Alani: 78.5
Daire Alani: 28.26
106.76


In [47]:
# daire cevresi hesaplama: 2*pi*r
def daireCevresiHesapla(r):
  PI = 3.14
  daire_cevresi = 2*PI*r
  return daire_cevresi

In [49]:
daire_cevresi_hesaplanan = daireCevresiHesapla(5)
print(f"hesapladigimiz daire ccevresi: {daire_cevresi_hesaplanan}")

hesapladigimiz daire ccevresi: 31.400000000000002


#### Veri Tipi: LISTE

In [2]:
liste = ["sut", "yumurta", "ekmek"]
liste

['sut', 'yumurta', 'ekmek']

In [4]:
liste_fiyat = [10,20,30] 
liste_fiyat

[10, 20, 30]

In [5]:
type(liste_fiyat)

list

In [5]:
hafta_liste = ["pazartesi", "sali", "cars", "persembe", "cuma","cumertesi", "pazar"]

In [6]:
print(hafta_liste[:3])
print(hafta_liste[3:])
print(hafta_liste[3:7])
print(hafta_liste[-4:])

['pazartesi', 'sali', 'cars']
['persembe', 'cuma', 'cumertesi', 'pazar']
['persembe', 'cuma', 'cumertesi', 'pazar']
['persembe', 'cuma', 'cumertesi', 'pazar']


In [7]:
###
sayi_listesi = [1,3,2,4,6,5]
sayi_listesi

[1, 3, 2, 4, 6, 5]

In [29]:
sayi_listesi.append(6)

In [25]:
sayi_listesi

[1, 3, 2, 5, 7, 7, 6, 5, 4, 5]

In [26]:
sayi_listesi.remove(6)

In [27]:
sayi_listesi

[1, 3, 2, 5, 7, 7, 5, 4, 5]

In [41]:
sorted(sayi_listesi)

[1, 2, 3, 4, 5, 5, 5, 6, 6, 7, 7]

#### Veri Tipi: Tuple

In [40]:
tuple_sayi = (1,2,3,3,3,4,5,6)
print(tuple_sayi[-2])
print(tuple_sayi[1])
print(tuple_sayi[1:])
print(tuple_sayi.count(3))  # tuple icerisinde bulunan istedigimiz elemani sayma

5
2
(2, 3, 3, 3, 4, 5, 6)
3


#### Veri Tipi: Dictionary
        anahtar-deger : key-value pair

In [43]:
dictionary = {"anahtar" : 10,
              "key": "ankara"}
dictionary

{'anahtar': 10, 'key': 'ankara'}

In [60]:
sehirler_plakalar ={
                        "ankara": 6,
                        "izmir" : 35,
                        "istanul": 34,
                        "kayseri": 38
}

In [61]:
sehirler_plakalar.keys()

dict_keys(['ankara', 'izmir', 'istanul', 'kayseri'])

In [62]:
sehirler_plakalar.values()

dict_values([6, 35, 34, 38])

In [63]:
sehirler_plakalar["izmir"]

35

In [70]:
"""
parameters = {"weights": [],
              "bias": [],
              "learning_rate": 0,
              "model_name": "model1"
             }
list_parameters = []
list_parameters.append(parameters)

"""

'\nparameters = {"weights": [],\n              "bias": [],\n              "learning_rate": 0,\n              "model_name": "model1"\n             }\nlist_parameters = []\nlist_parameters.append(parameters)\n\n'

#### Veri Tipleri Donusumleri

In [72]:
metin = "16"
kesirlisayi = 10.5
tamsayi = 10

In [73]:
# str -> int
metin_int = int(metin)
print(metin_int)
print(type(metin_int))

16
<class 'int'>


In [78]:
# float -> int
kesirlisayi_int = int(kesirlisayi)
print(kesirlisayi_int)
print(type(kesirlisayi_int))

10
<class 'int'>


In [79]:
# float -> str
kesirlisayi_str = str(kesirlisayi)
kesirlisayi_str

'10.5'

In [81]:
# int -> float
tamsayi_float = float(tamsayi)
tamsayi_float

10.0

In [82]:
# int -> str
tamsayi_str = str(tamsayi)
tamsayi_str

'10'

#### IF - ELSE

In [87]:
haftanin_gunleri = ["pazartesi", "sali", "cars", "persembe", "cuma","cumertesi", "pazar"]
if haftanin_gunleri[2] == "pazartesi":
        print("Pazartesi gunu listenin ikinci indeksinde")
else:
        print("Pazartesi gunu listenin ikinci indeksinde degil")

Pazartesi gunu listenin ikinci indeksinde degil


#### FOR LOOP


In [88]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [91]:
for i in "pazartesi sali":
    print(i)

p
a
z
a
r
t
e
s
i
 
s
a
l
i


In [102]:
"""
problem : NLP, elimizde str olarak cumle var. Mesela: "Bugun Python Dersimiz Var."
["bugun","python","dersimiz","var."]

"""

cumle = "Bugun Python Dersimiz Var."
liste_cumle = cumle.split()
liste_cumle

liste = []
for i in liste_cumle:
    kelime_kucuk_harf = i.lower()
    liste.append(kelime_kucuk_harf)
    ## print(kelime_kucuk_harf)
print(liste)

['bugun', 'python', 'dersimiz', 'var.']


In [103]:
"""
problem: liste = [1,2,3,4,5,6]
fonksiyon
    girdi: liste
    cikti: listenin  icinde bulunan cift sayilarun toplami

"""
liste = [1, 2, 3, 4, 5, 6]
def cift_sayilarin_toplami(liste):
    toplam = 0
    for i in liste:
        if i % 2 == 0:
            toplam += i
    return toplam

sonuc = cift_sayilarin_toplami(liste)
print("Çift sayıların toplamı:", sonuc)



Çift sayıların toplamı: 12


# Numpy

In [106]:
import numpy as np

In [109]:
# numpy array olusturma
liste = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
dizi = np.array(liste)
dizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [113]:
# arrau boyutu
dizi.shape     # (15,0) -> 15x1 lik bir vektor

(15,)

In [116]:
# 15x1 lik bir arrayi 3x5 lik bir matrise cevirme
dizi2 = dizi.reshape(3,5)
dizi2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [121]:
print("shape:", dizi2.shape)
print("dimension(boyut):", dizi2.ndim)
print("size:", dizi2.size)
print("type:", type(dizi2))

shape: (3, 5)
dimension(boyut): 2
size: 15
type: <class 'numpy.ndarray'>


In [123]:
dizi2D = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,5]])
dizi2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 5]])

In [124]:
# sifirlardan olusan bir array olusturma

sifirdizisi = np.zeros((3,4))
sifirdizisi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [140]:
# birlerden olusan bir array olusturma

birdizisi = np.ones((3,4,5))
birdizisi

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [141]:
# bos bir array olusturma
bosdizi = np.empty((2,4))
bosdizi

array([[4.67296746e-307, 1.69121096e-306, 1.02361682e-306,
        1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.29061142e-306]])

In [134]:
# arange (x,y,basamak) x den baslar y ye (y dahil degil) kadar gider basamak buyuklugunde artarak ilerler
# 10, 50, basamak =5
dizi_aralik = np.arange(10,50,5)
dizi_aralik

array([10, 15, 20, 25, 30, 35, 40, 45])

In [139]:
# linspace (x,y,basamak) x ve y(dahil) araliginda basamak kadar sayiya boler
dizi_bosluk = np.linspace(10,50,9)
dizi_bosluk

array([10., 15., 20., 25., 30., 35., 40., 45., 50.])

##  Numpy Temel Operasyonlari


In [142]:
import numpy as np

In [143]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [149]:
print("Toplama: ", a+b)
print("Cikartma: ", a-b)
print("Carpma: ", a*b)
print("Bolme: ", a/b)
print("Karesi: ", a**2)
print("Kupu: ", a**3)

Toplama:  [5 7 9]
Cikartma:  [-3 -3 -3]
Carpma:  [ 4 10 18]
Bolme:  [0.25 0.4  0.5 ]
Karesi:  [1 4 9]
Kupu:  [ 1  8 27]


In [150]:
# Filtreleme
a = np.array([1,2,3])
a < 2                  # a arrayinin icinde bulunan 2 den kucuk degerleri goster

array([ True, False, False])

In [154]:
# matris carpimi
a = np.array([[1,2,3],
              [4,5,6]])  # 2x3

b = np.array([[4,5,6],
              [1,2,3]])  # 2x3  -> Transpose aliniyor 3x2
a.dot(b.T)

array([[32, 14],
       [77, 32]])

In [157]:
a = np.array([[1,2,3],
              [4,5,6]])  # 2x3
print(sum(a))
print(np.sum(a))
print(a.sum())

[5 7 9]
21
21


In [160]:
print(a.max())
print(a.min())
print(np.max(a))
print(np.min(a))

6
1
6
1


In [163]:
# satir satir toplama
print(a.sum(axis = 1))
# sutun sutun toplama
print(a.sum(axis = 0))

[ 6 15]
[5 7 9]


In [164]:
# sqrt (karekok alma)
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [166]:
# kare alma
print(np.square(a))
print(a**2)

[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]


In [170]:
# Rastgele sayi uretme
rastgele_dizi = np.random.random((3,3))  # Normal dagilima gore 0-1
rastgele_dizi

array([[0.39260077, 0.78847067, 0.81281221],
       [0.13057888, 0.70845491, 0.97070777],
       [0.07674164, 0.20379088, 0.98291791]])

In [174]:
# Rastgele sayi uretme
rastgele_dizi = np.random.normal(0,1,10)  # Normal dagilima gore 0 ortalamali 1 std sapmali, 5 deger uret
rastgele_dizi

array([ 0.40784994, -0.09785833,  0.25192747,  0.26971173, -1.36117496,
        1.11739046, -1.07377893,  0.77390593, -1.53563864,  0.03717564])

In [176]:
np.random.rand(3,3)

array([[0.00985215, 0.58497971, 0.68393195],
       [0.29428173, 0.07759675, 0.85253183],
       [0.26860851, 0.47679097, 0.55527314]])

In [177]:
np.random.normal(0,1,(5,3))

array([[-0.09685962,  0.69649851, -0.35825255],
       [-0.72555511, -0.26451843,  0.40789998],
       [ 1.1322619 ,  0.06906576,  0.07124411],
       [-1.08980426, -1.21804316, -0.84907533],
       [ 0.4957774 ,  1.10204591, -1.01278016]])

## Shape Manipulation


In [189]:
"""
1) A array = 2 boyutlu bir tane array -> (3,5)
2) B array = 1 boyutlu bir tane array -> (15,)
3) B array'ini (3,5) olacak sekilde reshape yapalim
4) C = A + B
5) D=linspace ve E=arange ile (3,5) lik matrisler olusturalim.
6) F = D + E
7) C'nin ve F'nin her bir elemanini for dongusu ile eleman eleman carpip G = (15,1) boyutunda elde edelim.
"""
import numpy as np
# 2 boyutlu bir dizi oluşturma (3x5)
A = np.random.rand(3, 5)  # 0 ile 1 arasında rastgele sayılarla dolu 3x5'lik bir dizi
# 1 boyutlu bir dizi oluşturma (15 elemanlı)
B = np.arange(15)  # 0'dan 14'e kadar sayıları içeren bir dizi
# B dizisini 3x5 boyutunda yeniden şekillendirme
B = B.reshape(3, 5)
# A ve B dizilerini toplama
C = A + B
D=np.linspace(10,50,15).reshape(3,5)
E=np.arange(10,160,10).reshape(3,5)
F=D+E
G = []
for i in range(C.shape[0]):  # 3
    for j in range(C.shape[1]):  # 5
        G.append(C[i, j] * F[i, j])

# Sonuçları ekrana yazdıralım
print("A array:")
print(A)

print("\nB array (reshape edilmiş):")
print(B)

print("\nC array (A + B):")
print(C)

print("\nD array (linspace ile oluşturulan):")
print(D)

print("\nE array (arange ile oluşturulan):")
print(E)

print("\nF array (D + E):")
print(F)

print("\nG array (C ve F'nin elemanlarının çarpımı, 15x1):")
print(G)
# print("G shape: ",np.array(G).shape)

# 8) C ve F'yi (15, 1) şekline getirip koşulu kontrol etme
C_flat = C.reshape(-1, 1)  # -1 otomatik olarak 15 elemanı kullanır
F_flat = F.reshape(-1, 1)

# G1 ve G2 listelerini tanımlama
G1 = []
G2 = []

# C'nin ilk elemanı ve F'nin son elemanı toplama işlemi ile ilerleme
for i in range(len(C_flat)):  # C_flat'in uzunluğunu kullanarak döngüyü oluştur
    toplam = C_flat[i, 0] + F_flat[len(F_flat) - 1 - i, 0]  # len kullanarak sondan eleman al
    if toplam > 1:
        G1.append(toplam)
    else:
        G2.append(toplam)

# Sonuçları yazdırma
print("G1 (Toplam > 1 olanlar):", G1)
print("G2 (Toplam <= 1 olanlar):", G2)

A array:
[[0.49286535 0.94945487 0.45126095 0.31752797 0.30220981]
 [0.70168465 0.71544286 0.67357402 0.2942029  0.42246344]
 [0.92192858 0.31935084 0.91052807 0.1813264  0.08161332]]

B array (reshape edilmiş):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

C array (A + B):
[[ 0.49286535  1.94945487  2.45126095  3.31752797  4.30220981]
 [ 5.70168465  6.71544286  7.67357402  8.2942029   9.42246344]
 [10.92192858 11.31935084 12.91052807 13.1813264  14.08161332]]

D array (linspace ile oluşturulan):
[[10.         12.85714286 15.71428571 18.57142857 21.42857143]
 [24.28571429 27.14285714 30.         32.85714286 35.71428571]
 [38.57142857 41.42857143 44.28571429 47.14285714 50.        ]]

E array (arange ile oluşturulan):
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]

F array (D + E):
[[ 20.          32.85714286  45.71428571  58.57142857  71.42857143]
 [ 84.28571429  97.14285714 110.         122.85714286 135.71428571]
 [148.57142857 161.42857143 174.2857142